### ISSUE TITLE
[Bug]:  NullPointerException: Cannot invoke "sootup.core.jimple.basic.Local.getName()" because "newLocal" is null

### ISSUE THREAD

**Issue by sahilagichani14** [soot-oss/SootUp#1095]
### What happened?

executing jackson-core-2.14.2.jar with these body interceptors jb.cp,jb.dae,jb.cbf,jb.a,jb.lp

### Version

Latest develop branch

### Relevant log output

```shell
Exception in thread "main" java.lang.IllegalStateException: Failed to apply sootup.core.transform.RunTimeBodyInterceptor@798e519 to <com.fasterxml.jackson.core.util.BufferRecyclers: void <clinit>()>
	at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:241)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at upb.thesis.SetUp.lambda$setupSootUp$0(SetUp.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at upb.thesis.SetUp.lambda$setupSootUp$1(SetUp.java:189)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at upb.thesis.SetUp.setupSootUp(SetUp.java:188)
	at upb.thesis.SetUp.executeStaticAnalysis(SetUp.java:49)
	at upb.thesis.Main.main(Main.java:81)
Caused by: java.lang.NullPointerException: Cannot invoke "sootup.core.jimple.basic.Local.getName()" because "newLocal" is null
	at sootup.interceptors.LocalPacker.interceptBody(LocalPacker.java:115)
	at sootup.core.transform.RunTimeBodyInterceptor.interceptBody(RunTimeBodyInterceptor.java:54)
	at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:235)
	... 18 more
```

**Comment by sahilagichani14** [comment]
Handle below issue as well:

Exception in thread "main" java.lang.IllegalStateException: Failed to apply sootup.core.transform.RunTimeBodyInterceptor@5b0112f8 to <org.apache.commons.codec.digest.UnixCrypt: int fourBytesToInt(byte[],int)>
        at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:241)
        at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
        at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
        at upb.thesis.SetUp.lambda$setupSootUp$0(SetUp.java:191)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at upb.thesis.SetUp.lambda$setupSootUp$1(SetUp.java:189)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at upb.thesis.SetUp.setupSootUp(SetUp.java:188)
        at upb.thesis.SetUp.executeStaticAnalysis(SetUp.java:49)
        at upb.thesis.Main.main(Main.java:81)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at sootup.interceptors.LocalPacker.assignLocalsColor(LocalPacker.java:161)
        at sootup.interceptors.LocalPacker.interceptBody(LocalPacker.java:46)
        at sootup.core.transform.RunTimeBodyInterceptor.interceptBody(RunTimeBodyInterceptor.java:54)
        at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:235)
        ... 18 more

**Comment by sahilagichani14** [comment]
2 things that are wrong in the code.
- local.getUses() always returns an empty stream? To see if a local is used (implemented getOccurrences in local)
- removeDefLocalsOf(stmt) removes local from builder even if it occurs in stmts (like if condition)
