### ISSUE TITLE
[Bug]: Failed to apply sootup.interceptors.NopEliminator

### ISSUE THREAD

**Issue by palaniappan1** [soot-oss/SootUp#1120]
### What happened?

Failed to apply the NopEliminator.
More can be found in the branch [failed-jars-branch-20241014](https://github.com/soot-oss/SootUp/tree/failed-jars-branch-20241014)

### Version

Latest develop branch

### Relevant log output

```shell
java.lang.IllegalStateException: Failed to apply sootup.interceptors.NopEliminator@1e1a0406 to <io.github.adven27.concordion.extensions.exam.core.logger.LoggingFormatterExtension$LoggingFormatterListener: void afterExample(org.concordion.api.listener.ExampleEvent)>
	at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:242)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at sootup.java.bytecode.frontend.inputlocation.BaseFixJarsTest.assertMethodConversion(BaseFixJarsTest.java:28)
	at sootup.java.bytecode.frontend.inputlocation.FixJars.executeexamcorejar(FixJars.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by swissiety** [comment]
possibly the same as #1112

**Comment by sahilagichani14** [comment]
PR at: https://github.com/soot-oss/SootUp/pull/1146
