### ISSUE TITLE
AssertionError in WalaIRToJimpleConverter on throw new Exception

### ISSUE THREAD

**Issue by kadirayk** [soot-oss/SootUp#347]
Input: [Exception1.java](https://github.com/secure-software-engineering/PointerBench/blob/master/src/generalJava/Exception1.java)

Stack trace:
`java.lang.AssertionError
	at de.upb.swt.soot.java.sourcecode.frontend.WalaIRToJimpleConverter.createBody(WalaIRToJimpleConverter.java:582)
	at de.upb.swt.soot.java.sourcecode.frontend.WalaIRToJimpleConverter.convertMethod(WalaIRToJimpleConverter.java:270)
	at de.upb.swt.soot.java.sourcecode.frontend.WalaIRToJimpleConverter.convertToClassSource(WalaIRToJimpleConverter.java:168)
	at java.util.Optional.map(Optional.java:215)
	at de.upb.swt.soot.java.sourcecode.frontend.WalaJavaClassProvider.getClassSource(WalaJavaClassProvider.java:296)
	at de.upb.swt.soot.java.sourcecode.frontend.WalaJavaClassProvider.createClassSource(WalaJavaClassProvider.java:351)
	at de.upb.swt.soot.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.getClassSource(JavaSourcePathAnalysisInputLocation.java:112)
	at de.upb.swt.soot.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.getClassSource(JavaSourcePathAnalysisInputLocation.java:89)
	at de.upb.swt.soot.java.core.views.JavaView.lambda$getAbstractClass$1(JavaView.java:108)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.upb.swt.soot.java.core.views.JavaView.getAbstractClass(JavaView.java:114)
	at de.upb.swt.soot.java.core.views.JavaView.getClass(JavaView.java:89)
	at de.upb.swt.soot.callgraph.MethodUtil.methodSignatureToMethod(MethodUtil.java:38)
	at de.upb.swt.soot.callgraph.algorithm.AbstractCallGraphAlgorithm.resolveAllCallsFromSourceMethod(AbstractCallGraphAlgorithm.java:101)
	at de.upb.swt.soot.callgraph.algorithm.AbstractCallGraphAlgorithm.processWorkList(AbstractCallGraphAlgorithm.java:83)
	at de.upb.swt.soot.callgraph.algorithm.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:64)
	at de.upb.swt.soot.callgraph.algorithm.ClassHierarchyAnalysisAlgorithm.initialize(ClassHierarchyAnalysisAlgorithm.java:48)
	at de.upb.swt.soot.test.callgraph.spark.PointerBenchGeneralJavaTest.setUp(PointerBenchGeneralJavaTest.java:63)
	at de.upb.swt.soot.test.callgraph.spark.PointerBenchGeneralJavaTest.testException1(PointerBenchGeneralJavaTest.java:251)`

**Comment by mei71** [comment]
Hello, have you solved your problem? I have encountered the same problem.
