### ISSUE TITLE
native function java.lang.NullPointerException

### ISSUE THREAD

**Issue by Y4er** [soot-oss/SootUp#519]
When I was testing the implementation of taint analysis using ifds, i got java.lang.NullPointerException.

Here are the steps to reproduce:

1. edit `sootup.analysis/src/test/resources/taint/source/SimpleTaint.java`

```java
import java.util.ArrayList;

public class SimpleTaint {

    static int k;

    public void entryPoint() {
        int i = 1;
        int j = i;
        k = i;
        String a = "asd";
        String b = "asd";
        ArrayList<String> list = new ArrayList<>();
        list.add(a);
    }
}
```

2. change `sootup.analysis.interprocedural.ifds.IFDSTaintTestSetUp#setupSoot` use `new JavaSourcePathAnalysisInputLocation("src/test/resources/taint/source"))`

3. run `sootup.analysis.interprocedural.ifds.IFDSTaintAnalysisTest#SimpleTaint` get this

```
[main] INFO sootup.core.typehierarchy.ViewTypeHierarchy - Type hierarchy scan took 2104.2979 ms
[main] INFO sootup.core.typehierarchy.ViewTypeHierarchy - Type hierarchy scan took 29.5315 ms
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "float invokeBasic(java.lang.invoke.BoundMethodHandle)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "int invokeBasic(java.lang.invoke.BoundMethodHandle)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "long invokeBasic(java.lang.invoke.BoundMethodHandle)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "double invokeBasic(java.lang.invoke.BoundMethodHandle)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.Object invokeBasic(java.lang.invoke.BoundMethodHandle)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.Object invoke()" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,java.lang.Object,java.lang.Object)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,float)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,java.lang.Object,float)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,double)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,java.lang.Object,double)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,java.lang.Object,long)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,long)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,int)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.invoke.BoundMethodHandle invokeBasic(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm,java.lang.Object,int)" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "java.lang.Object invokeExact(java.lang.invoke.MethodHandle,java.lang.Object[])" in MethodHandle and in its superclasses
[main] WARN sootup.callgraph.AbstractCallGraphAlgorithm - Could not find "void invokeExact()" in MethodHandle and in its superclasses

java.lang.NullPointerException
	at sootup.analysis.interprocedural.icfg.AbstractJimpleBasedICFG.initializeStmtToOwner(AbstractJimpleBasedICFG.java:225)
	at sootup.analysis.interprocedural.icfg.JimpleBasedInterproceduralCFG.initializeStmtToOwner(JimpleBasedInterproceduralCFG.java:160)
	at sootup.analysis.interprocedural.icfg.JimpleBasedInterproceduralCFG.<init>(JimpleBasedInterproceduralCFG.java:148)
	at sootup.analysis.interprocedural.ifds.IFDSTaintTestSetUp.runAnalysis(IFDSTaintTestSetUp.java:62)
	at sootup.analysis.interprocedural.ifds.IFDSTaintTestSetUp.executeStaticAnalysis(IFDSTaintTestSetUp.java:53)
	at sootup.analysis.interprocedural.ifds.IFDSTaintAnalysisTest.SimpleTaint(IFDSTaintAnalysisTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by swissiety** [comment]
Hi @Y4er,
thx for your report!
I created a PR which should fix the NPEs you found.
