### ISSUE TITLE
failed to load root <Primordial,Ljava/lang/Object> of class hierarchy

### ISSUE THREAD

**Issue by cyberhorse208** [soot-oss/SootUp#588]
i create a new maven project to use sootup, code just like  [BasicSetup](https://github.com/soot-oss/SootUp/blob/develop/sootup.examples/src/test/java/sootup/examples/basicSetup/BasicSetup.java)

public static void createSourceCodeProject() {
        Path pathToSource = Paths.get("src/test/resources/BasicSetup/source");
        AnalysisInputLocation<JavaSootClass> inputLocation =
                new JavaSourcePathAnalysisInputLocation(pathToSource.toString());
        Language language = new JavaLanguage(8);
        Project project =
                JavaProject.builder((JavaLanguage) language).addInputLocation(inputLocation).build();
        // Create a signature for the class we want to analyze
        ClassType classType = project.getIdentifierFactory().getClassType("HelloWorld");
        // Create a signature for the method we want to analyze
        MethodSignature methodSignature =
                project
                        .getIdentifierFactory()
                        .getMethodSignature(
                                classType, "main", "void", Collections.singletonList("java.lang.String[]"));

        // Create a view for project, which allows us to retrieve classes
        View view = project.createFullView();
  
       //...
}

src/test/resources/BasicSetup/source has file [HelloWorld.java](https://github.com/soot-oss/SootUp/blob/develop/sootup.examples/src/test/resources/BasicSetup/source/HelloWorld.java) 

**but i got error like this:**

`com.ibm.wala.ipa.cha.ClassHierarchyException: failed to load root <Primordial,Ljava/lang/Object> of class hierarchy
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:299)
	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:203)
	at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:85)
	at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:71)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.buildClassHierachy(WalaJavaClassProvider.java:216)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.iterateWalaClasses(WalaJavaClassProvider.java:267)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.getClassSources(WalaJavaClassProvider.java:229)
	at sootup.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.getClassSources(JavaSourcePathAnalysisInputLocation.java:153)
	at sootup.java.core.views.JavaView.lambda$resolveAll$3(JavaView.java:163)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at sootup.java.core.views.JavaView.resolveAll(JavaView.java:164)
	at sootup.java.core.views.JavaView.getClasses(JavaView.java:104)
	at sootup.java.core.JavaProject.createFullView(JavaProject.java:78)
	at sootup.java.core.JavaProject.createFullView(JavaProject.java:45)
	at com.vivo.kmirrors.playground.playsootup.BasicSetup.createSourceCodeProject(BasicSetup.java:49)
	at com.vivo.kmirrors.playground.playsootup.BasicSetup.main(BasicSetup.java:148)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.ibm.wala.ipa.cha.IClassHierarchy.getLoader(com.ibm.wala.types.ClassLoaderReference)" because "this.classHierarchy" is null
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.iterateWalaClasses(WalaJavaClassProvider.java:272)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.getClassSources(WalaJavaClassProvider.java:229)
	at sootup.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.getClassSources(JavaSourcePathAnalysisInputLocation.java:153)
	at sootup.java.core.views.JavaView.lambda$resolveAll$3(JavaView.java:163)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at sootup.java.core.views.JavaView.resolveAll(JavaView.java:164)
	at sootup.java.core.views.JavaView.getClasses(JavaView.java:104)
	at sootup.java.core.JavaProject.createFullView(JavaProject.java:78)
	at sootup.java.core.JavaProject.createFullView(JavaProject.java:45)
	at com.vivo.kmirrors.playground.playsootup.BasicSetup.createSourceCodeProject(BasicSetup.java:49)
	at com.vivo.kmirrors.playground.playsootup.BasicSetup.main(BasicSetup.java:148)

Process finished with exit code 1`

Is there something wrong with my code ?
can anyone check it for me? 
thanks a lot.

**Comment by swissiety** [comment]
My first guess would be the code was not executed in a Java8 JVM. Currently, the sourcecode frontend needs to be run with Java8.

**Comment by cyberhorse208** [comment]
i change to java 8, and still got the same error.

btw, i can run junit without such error in the sootup.example , like BasicSetup.createSourceCodeProject with JDK 11.

**Comment by JonasKlauke** [comment]
You need to add your JVMs Runtime Jar as an InputLocation.
Object is a class provided by Java but if you do not add the rt.jar as inputlocation SootUp can not find it.
So you need to change it to:
```
Project project = JavaProject.builder((JavaLanguage) language)
  .addInputLocation(
    new JavaClassPathAnalysisInputLocation(
      System.getProperty("java.home") + "/lib/rt.jar")) //add rt.jar
  .addInputLocation(inputLocation).build();
```

**Comment by hungkien05** [comment]
Hi @cyberhorse208 , have you found the solution for this yet ? I also run into this error. Thanks

**Comment by hungkien05** [comment]
Hi @JonasKlauke , I did add the runtime jar as you instructed but still got the same error.

**Comment by JonasKlauke** [comment]
are you analysing android apps? then you might have to add the android.jar to find the Object class.

**Comment by JonasKlauke** [comment]
> Hi @JonasKlauke , I did add the runtime jar as you instructed but still got the same error.

Do you still have the issue? You might have to set the JAVA_HOME environment variable.
