### ISSUE TITLE
How to parallelize?

### ISSUE THREAD

**Issue by ceclin** [soot-oss/SootUp#591]
I use `javaView.getClasses().parallelStream()` to retrieve some information for all classes.

But it throws `java.util.ConcurrentModificationException`:
```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
	at sootup.java.core.JavaIdentifierFactory.getPackageName(JavaIdentifierFactory.java:254)
Caused by: java.util.ConcurrentModificationException
	at sootup.java.core.JavaIdentifierFactory.getClassType(JavaIdentifierFactory.java:108)
	at sootup.java.core.JavaIdentifierFactory.getClassType(JavaIdentifierFactory.java:122)
	at sootup.java.core.JavaIdentifierFactory.lambda$getType$1(JavaIdentifierFactory.java:175)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at sootup.java.core.JavaIdentifierFactory.getType(JavaIdentifierFactory.java:175)
	at sootup.java.bytecode.frontend.AsmUtil.toJimpleType(AsmUtil.java:200)
	at sootup.java.bytecode.frontend.AsmClassSource.lambda$resolveFields$0(AsmClassSource.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at sootup.java.bytecode.frontend.AsmClassSource.resolveFields(AsmClassSource.java:75)
	at sootup.java.bytecode.frontend.AsmClassSource.resolveFields(AsmClassSource.java:147)
	at sootup.core.model.SootClass.lazyFieldInitializer(SootClass.java:63)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:166)
	at sootup.core.model.SootClass.getFields(SootClass.java:106)
	at sootup.java.core.JavaSootClass.getFields(JavaSootClass.java:109)
```

It seems that `sootup.java.core.JavaIdentifierFactory` is still a global singleton and in this class `java.util.HashMap` is used for cache, which doesn't support concurrency.

Is that exception expected? What is the correct way to parallelize?

**Comment by swissiety** [comment]
Thanks for finding (and reporting) it!

The intention was to create some kind of 'canonical mapping' i.e. save some memory for the possibly huge amount of (duplicate) signatures while enabling for reference-equality checks.

As a quick fix a `ConcurrentHashmap` instead of the Hashmap should work as intended - maybe you like to create a PR?

I think the better solution would be incorporating weak references and enabling unused signature for GC. So with guava something like: `ConcurrentMap<String, PackageName> cache = new MapMaker().weakValues().makeComputingMap( respectiveInstantiateFunc )` should do the job.

**Comment by ceclin** [comment]
Thanks for your explanation! I've learned a lot from it.
