### ISSUE TITLE
wala.properties not found while trying to analyis source code

### ISSUE THREAD

**Issue by Akkyen** [soot-oss/SootUp#594]
OS: Windows11
JDK: 15.0.2

I tried to create the path by myself but i doesn't seem to be able to pin point the correct location.
I want to analyse the DBeaver java application.
Wouldn't it be better to create the path and file automatically?

path in walaPropertiesFile="target\classes\wala.properties"

Source Code line in which the error occures:
`AnalysisInputLocation<JavaSootClass> inputLocation = new JavaSourcePathAnalysisInputLocation(pathToSources.toString());`

My path goes to an src folder like ".../StandaloneApplication/.../src/"

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: target\classes\wala.properties (The system can not find the path specified)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.createWalaproperties(WalaJavaClassProvider.java:191)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.addScopesForJava(WalaJavaClassProvider.java:197)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.<init>(WalaJavaClassProvider.java:88)
	at sootup.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.<init>(JavaSourcePathAnalysisInputLocation.java:86)
	at sootup.java.sourcecode.inputlocation.JavaSourcePathAnalysisInputLocation.<init>(JavaSourcePathAnalysisInputLocation.java:73)
	at TestSootUp.main(TestSootUp.java:29)
Caused by: java.io.FileNotFoundException: target\classes\wala.properties (The system can not find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at java.base/java.io.PrintWriter.<init>(PrintWriter.java:309)
	at sootup.java.sourcecode.frontend.WalaJavaClassProvider.createWalaproperties(WalaJavaClassProvider.java:186)
	... 5 more

Also please update all your documentation or replace your website with an notice that this software is currently not usable for production

**Comment by swissiety** [comment]
I guess you're using gradle and the maven release? I guess this bug is already fixed in develop (as a dirty quick fix: just create the folder structure target/classes/ and the wala.properties file should be created automatically)
