### ISSUE TITLE
Caching Strategy seems to close class files which are later used

### ISSUE THREAD

**Issue by Akkyen** [soot-oss/SootUp#610]
Im trying to analyze multiple jar files on linux.

```
List<String> result;

        try (Stream<Path> walk = Files.walk(new File("/home/***/Downloads/dbeaver/plugins/").toPath(), 100))
        {
             result = walk
                    .filter(p -> !Files.isDirectory(p))
                    .map(Path::toString)
                    .filter(f -> f.endsWith("jar"))
                    .collect(Collectors.toList());
        } catch (IOException e)
        {
            throw new RuntimeException(e);
        }

        ArrayList<AnalysisInputLocation<JavaSootClass>> inputLocations = new ArrayList<>();

        for (String s : result)
        {
            inputLocations.add(new PathBasedAnalysisInputLocation(Paths.get(s), SourceType.Library));
        }

        // Specify the language of the JavaProject. This is especially relevant for Multi-release jars,
        // where classes are loaded depending on the language level of the analysis
        JavaLanguage language = new JavaLanguage(6);

        // Create a new JavaProject and view based on the input location
        JavaProject.JavaProjectBuilder projectBuilder = JavaProject.builder(language);

        for (AnalysisInputLocation<JavaSootClass> a : inputLocations)
        {
            projectBuilder.addInputLocation(a);
        }

        JavaProject project = projectBuilder.build();

        JavaView view = project.createView();


        ClassType classTypeA = project.getIdentifierFactory().getClassType("org.jkiss.dbeaver.ui.app.standalone.ApplicationActionBarAdvisor");

        MethodSignature entryMethodSignature =
                JavaIdentifierFactory.getInstance()
                        .getMethodSignature(classTypeA,
                                "removeUnWantedActions",
                                "void",
                                Collections.emptyList());

        // Create type hierarchy and CHA
        ViewTypeHierarchy typeHierarchy = new ViewTypeHierarchy(view);

        //System.out.println(typeHierarchy.subclassesOf(classTypeA));
        //System.out.println(typeHierarchy.subclassesOf(classTypeA));
        CallGraphAlgorithm cha = new RapidTypeAnalysisAlgorithm(view);
        // Create CG by initializing CHA with entry method(s)
        CallGraph cg = cha.initialize(Collections.singletonList(entryMethodSignature));

        cg.callsFrom(entryMethodSignature).forEach(System.out::println);
    }
```
And I'm getting this error message:
```


Exception in thread "main" java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1635)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.checkAccess(ZipFileSystem.java:560)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.checkAccess(ZipPath.java:898)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:172)
	at java.base/java.nio.file.Files.exists(Files.java:2526)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSourceInternal(PathBasedAnalysisInputLocation.java:227)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$DirectoryBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:252)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:143)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$MultiReleaseJarAnalysisInputLocation.lambda$getClassSource$5(PathBasedAnalysisInputLocation.java:406)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$MultiReleaseJarAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:410)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:143)
	at sootup.java.core.views.JavaView.lambda$getAbstractClass$1(JavaView.java:160)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at sootup.java.core.views.JavaView.getAbstractClass(JavaView.java:166)
	at sootup.java.core.views.JavaView.getClass(JavaView.java:143)
	at sootup.core.views.AbstractView.getMethod(AbstractView.java:91)
	at sootup.callgraph.AbstractCallGraphAlgorithm.lambda$constructCompleteCallGraph$0(AbstractCallGraphAlgorithm.java:85)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4966)
	at sootup.callgraph.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:82)
	at sootup.callgraph.RapidTypeAnalysisAlgorithm.initialize(RapidTypeAnalysisAlgorithm.java:91)
	at TestSootUp.main(TestSootUp.java:87)
Disconnected from the target VM, address: '127.0.0.1:56087', transport: 'socket'

Process finished with exit code 1
```

**Comment by Akkyen** [comment]
It seems this error is not consistent and I'm not reliably able to reproduce it

**Comment by Akkyen** [comment]
I added the code:

`var a = view.getClasses();`

I'm getting it consistently now.

**Comment by JonasKlauke** [comment]
Hi, I assume you are using v1.1 because of the createView method. Is that correct?
You have configured Java 6 is that correct? :)
Because you are inputting paths to jars, could you try to use JavaClassPathAnalysisInputLocation instead of PathBasedAnalysisInputLocation. Do you get the same issue?

**Comment by Akkyen** [comment]
Yes i am using SootUp v1.1.
I already used 17 which is the version of the project I'm trying to analyze but same error message.
Just tried a bit around and forgot to change it.
I tried using JavaClassPathAnalysisInputLocation still getting 

```
Exception in thread "main" java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1635)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.checkAccess(ZipFileSystem.java:560)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.checkAccess(ZipPath.java:898)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:172)
	at java.base/java.nio.file.Files.exists(Files.java:2526)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSourceInternal(PathBasedAnalysisInputLocation.java:227)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$DirectoryBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:252)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:143)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$MultiReleaseJarAnalysisInputLocation.lambda$getClassSource$5(PathBasedAnalysisInputLocation.java:406)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation$MultiReleaseJarAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:410)
	at sootup.java.bytecode.inputlocation.PathBasedAnalysisInputLocation.getClassSource(PathBasedAnalysisInputLocation.java:143)
	at sootup.java.bytecode.inputlocation.JavaClassPathAnalysisInputLocation.getClassSource(JavaClassPathAnalysisInputLocation.java:196)
	at sootup.java.core.views.JavaView.lambda$getAbstractClass$1(JavaView.java:160)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at sootup.java.core.views.JavaView.getAbstractClass(JavaView.java:166)
	at sootup.java.core.views.JavaView.getClass(JavaView.java:143)
	at sootup.core.views.View.getClassOrThrow(View.java:95)
	at sootup.core.typehierarchy.ViewTypeHierarchy.sootClassFor(ViewTypeHierarchy.java:411)
	at sootup.core.typehierarchy.ViewTypeHierarchy.superClassOf(ViewTypeHierarchy.java:292)
	at sootup.core.typehierarchy.TypeHierarchy.incompleteSuperClassesOf(TypeHierarchy.java:199)
	at sootup.callgraph.AbstractCallGraphAlgorithm.lambda$resolveAllStaticInitializerCallsFromSourceMethod$5(AbstractCallGraphAlgorithm.java:248)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at sootup.callgraph.AbstractCallGraphAlgorithm.processWorkList(AbstractCallGraphAlgorithm.java:144)
	at sootup.callgraph.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:97)
	at sootup.callgraph.RapidTypeAnalysisAlgorithm.initialize(RapidTypeAnalysisAlgorithm.java:91)
	at TestSootUp.main(TestSootUp.java:92)

Process finished with exit code 1
```

**Comment by swissiety** [comment]
the problem seems to be with a cached reference to an already closed filesystem which loads "later" ondemand more information from an then closed filesystem and therefore throws an exception.. a similar situation occurs with later accessed/loaded annotations.

**Comment by JonasKlauke** [comment]
duplicate to issue #527
