### ISSUE TITLE
Aggregator type cast bug

### ISSUE THREAD

**Issue by virusdefender** [soot-oss/SootUp#739]
```java
public class Main  {
  public static void main(String[] args) {
    int a = Integer.valueOf(args[0]);
    int b = a;
    int c = b;
    System.out.println(a + b + c);

  }
}
```

and then enable body interceptor

```kotlin
view.configBodyInterceptors{
        BytecodeClassLoadingOptions.Default
    }
```

```
java.lang.IllegalStateException: Failed to apply sootup.java.bytecode.interceptors.Aggregator@662ac478 to <Main: void main(java.lang.String[])>
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:229)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
Caused by: java.lang.ClassCastException: class sootup.core.jimple.common.expr.JAddExpr cannot be cast to class sootup.core.jimple.basic.Immediate (sootup.core.jimple.common.expr.JAddExpr and sootup.core.jimple.basic.Immediate are in unnamed module of loader 'app')
	at sootup.java.bytecode.interceptors.Aggregator.interceptBody(Aggregator.java:196)
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:226)
	... 13 more
```

![image](https://github.com/soot-oss/SootUp/assets/4939404/16f749a9-5738-4b0a-8c94-f9af4a840e6a)

**Comment by swissiety** [comment]
Hi @virusdefender
which version of SootUp do you use?

**Comment by virusdefender** [comment]
> Hi @virusdefender which version of SootUp do you use?

the `develop` branch with commit 647da14028d93f58a9b416160c99a7569cf3bce8

build by my self

**Comment by swissiety** [comment]
~~did you compile the input? if yes, please upload the .class, because i couldn't reproduce the error (maybe I used a different compiler/version?)~~ expected bodyinterceptors where already enabled by default

**Comment by virusdefender** [comment]
[Main.class.zip](https://github.com/soot-oss/SootUp/files/13250617/Main.class.zip)

```
java -version
java version "17.0.3.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)
```

if the  body interceptor is not enabled, the generated jimple is

```jimple
{
    java.lang.String[] $l0;
    unknown $l1, $l2, $l3, $stack4, $stack5, $stack6, $stack7, $stack8;


    $l0 := @parameter0: java.lang.String[];
    $stack4 = $l0[0];
    $stack5 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(java.lang.String)>($stack4);
    $l1 = virtualinvoke $stack5.<java.lang.Integer: int intValue()>();
    $l2 = $l1;
    $l3 = $l2;
    $stack8 = <java.lang.System: java.io.PrintStream out>;
    $stack6 = $l1 + $l2;
    $stack7 = $stack6 + $l3;
    virtualinvoke $stack8.<java.io.PrintStream: void println(int)>($stack7);

    return;
}

```

there are some `unknown` type variables, so i enabled the  body interceptor, but it will cause the above exception
