### ISSUE TITLE
Failure to Include rt.jar Leads to Errors While Adding rt.jar Results in Prolonged CG Construction Without Completion

### ISSUE THREAD

**Issue by LianKee** [soot-oss/SootUp#775]
I'm using SootUp to analyze a real-world program (i.e., Tomcat ). When constructing the Call Graph (CG), if I don't specify rt.jar as an InputLocation, an exception is thrown: `sootup.core.frontend.ResolveException: Could not find java.lang.Object in View. ./file-does-not-exist NoPositionInformation.` However, if I add it, the CG construction takes an extended period and the program gets stuck (maybe due to the analysis of JVM methods). Below is the specific key code and error message.

```
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello SootUp!");

        // 指定输入文件夹 - 字节码
        AnalysisInputLocation<JavaSootClass> analysisInputLocation = new JavaClassPathAnalysisInputLocation("/Users/liankeke/Desktop/Projects/code");
        // 指定Java版本
        JavaLanguage javaLanguage = new JavaLanguage(8);
        // SootUp 初始化
        Project<JavaSootClass, JavaView> project = JavaProject.builder(javaLanguage)
//                .addInputLocation(new JavaClassPathAnalysisInputLocation("src/libs/rt.jar"))
                .addInputLocation(analysisInputLocation)
                .build();
        // 创建一个View进行分析
        JavaView view = (JavaView) project.createView();

        ClassType classType = project.getIdentifierFactory().getClassType("org.apache.catalina.valves.CrawlerSessionManagerValve");

        MethodSignature methodSignature = project.getIdentifierFactory()
                .getMethodSignature(classType,"invoke","void", Arrays.asList("org.apache.catalina.connector.Request", "org.apache.catalina.connector.Response"));
        CallGraphAlgorithm cha = new ClassHierarchyAnalysisAlgorithm(view);
        CallGraph callGraph = cha.initialize(Collections.singletonList(methodSignature));

        System.out.println(callGraph.callCount());
   }
}
```

```
Exception in thread "main" sootup.core.frontend.ResolveException: Could not find java.lang.Object in View. ./file-does-not-exist NoPositionInformation
	at sootup.core.views.View.lambda$getClassOrThrow$0(View.java:93)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at sootup.core.views.View.getClassOrThrow(View.java:93)
	at sootup.core.typehierarchy.ViewTypeHierarchy.sootClassFor(ViewTypeHierarchy.java:411)
	at sootup.core.typehierarchy.ViewTypeHierarchy.superClassOf(ViewTypeHierarchy.java:292)
	at sootup.core.typehierarchy.TypeHierarchy.superClassesOf(TypeHierarchy.java:183)
	at sootup.callgraph.AbstractCallGraphAlgorithm.findMethodInHierarchy(AbstractCallGraphAlgorithm.java:271)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.lambda$resolveCall$1(ClassHierarchyAnalysisAlgorithm.java:89)
	at java.util.Optional.orElseGet(Optional.java:267)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.resolveCall(ClassHierarchyAnalysisAlgorithm.java:89)
	at sootup.callgraph.AbstractCallGraphAlgorithm.lambda$resolveAllCallsFromSourceMethod$3(AbstractCallGraphAlgorithm.java:176)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at sootup.callgraph.AbstractCallGraphAlgorithm.processWorkList(AbstractCallGraphAlgorithm.java:144)
	at sootup.callgraph.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:97)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.initialize(ClassHierarchyAnalysisAlgorithm.java:63)
	at org.example.Main.main(Main.java:78)
```

How can I resolve this? Thank you.

**Comment by LianKee** [comment]
I try to specify the rt.jar with SourceType.Library and get a new Exception:

```
Project<JavaSootClass, JavaView> project = JavaProject.builder(javaLanguage)
                .addInputLocation(new JavaClassPathAnalysisInputLocation("src/libs/rt.jar", SourceType.Library))
                .addInputLocation(analysisInputLocation)
                .build();


Exception in thread "main" sootup.core.frontend.ResolveException: Could not find org.apache.tools.ant.DefaultLogger in View. ./file-does-not-exist NoPositionInformation
	at sootup.core.views.View.lambda$getClassOrThrow$0(View.java:93)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at sootup.core.views.View.getClassOrThrow(View.java:93)
	at sootup.core.typehierarchy.ViewTypeHierarchy.sootClassFor(ViewTypeHierarchy.java:411)
	at sootup.core.typehierarchy.ViewTypeHierarchy.superClassOf(ViewTypeHierarchy.java:292)
	at sootup.core.typehierarchy.TypeHierarchy.superClassesOf(TypeHierarchy.java:183)
	at sootup.callgraph.AbstractCallGraphAlgorithm.findMethodInHierarchy(AbstractCallGraphAlgorithm.java:271)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.lambda$resolveCall$1(ClassHierarchyAnalysisAlgorithm.java:89)
	at java.util.Optional.orElseGet(Optional.java:267)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.resolveCall(ClassHierarchyAnalysisAlgorithm.java:89)
	at sootup.callgraph.AbstractCallGraphAlgorithm.lambda$resolveAllCallsFromSourceMethod$3(AbstractCallGraphAlgorithm.java:176)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at sootup.callgraph.AbstractCallGraphAlgorithm.processWorkList(AbstractCallGraphAlgorithm.java:144)
	at sootup.callgraph.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:97)
	at sootup.callgraph.ClassHierarchyAnalysisAlgorithm.initialize(ClassHierarchyAnalysisAlgorithm.java:63)
	at org.example.Main.main(Main.java:82)
```

PS: org.apache.tools.ant.DefaultLogger class file is not included in the analysisInputLocation

**Comment by LianKee** [comment]
Sometimes, when analyzing a real-world component A, the code of this component may use classes and functions from another component, for example, B. This is common in actual deployments where multiple components collaborate. Since our focus is on analyzing component A, and the code of component B is not included in InputLocation, would it be better if SootUp could automatically treat the classes and functions used from B as ghost functions in such cases?

**Comment by swissiety** [comment]
Hi @LianKee,
which version of SootUp do you use?

**Comment by LianKee** [comment]
Hi, I use the release v1.1.2, imported from maven.

**Comment by swissiety** [comment]
Ok, feel free to use SootUps develop branch (compiling&installing it yourself or e.g. via a [jitpack](https://jitpack.io/#soot-oss/SootUp/develop-SNAPSHOT) dependency) the mentioned issues should already be addressed there.

**Comment by JonasKlauke** [comment]
The SourceType Library does not prevent call graph algorithm from further exploring these libraries. This was recently fixed and will be included in the next version. 
The resolving of missing data was also changed to warnings instead of throwing an exception and stopping the analysis. This will be also included in the next version. 
For your current use case in the old version you have to include all libraries, or you use the current development state.
The second exception looks like a missed dependency

**Comment by LianKee** [comment]
Thanks for your responses. I tried to use the develop branch via the jitpack dependency. However, there exist some classes that can not be resolved. The details are as follows. Did I do something wrong?

```
pom.xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://www.jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.soot-oss</groupId>
            <artifactId>SootUp</artifactId>
            <version>develop-3cf4a05a28-1</version>
        </dependency>
    </dependencies>
```

<img width="595" alt="image" src="https://github.com/soot-oss/SootUp/assets/23692514/2f7b7bb2-c17a-4f66-8e92-92acce7fbf5c">

<img width="705" alt="image" src="https://github.com/soot-oss/SootUp/assets/23692514/5698550a-2152-4831-9964-eed2089071f8">

**Comment by JonasKlauke** [comment]
we changed the API of SootUp 😆 
We dropped the project Stuff. 
Now you put all input locations in the constructor of a view.
You can find the documentation here https://soot-oss.github.io/SootUp/develop/getting-started/

Edit: We should release a new version soon 😅

**Comment by LianKee** [comment]
Thank you for your assistance, my issue has been resolved. 😀
