### ISSUE TITLE
`sootup.core.frontend.ResolveException` when construct a callgraph

### ISSUE THREAD

**Issue by MaverickMango** [soot-oss/SootUp#830]
hi folks,
I'm trying to construct a call graph of it under jdk11, I have correctly got the `SootMethod` but met a `ResolveException`
```
Could not find java.lang.Object in View. ./file-does-not-exist NoPositionInformation
sootup.core.frontend.ResolveException: Could not find java.lang.Object in View. ./file-does-not-exist NoPositionInformation
	at app//sootup.core.views.View.lambda$getClassOrThrow$0(View.java:93)
	at java.base@11.0.19/java.util.Optional.orElseThrow(Optional.java:408)
	at app//sootup.core.views.View.getClassOrThrow(View.java:93)
	at app//sootup.core.typehierarchy.ViewTypeHierarchy.sootClassFor(ViewTypeHierarchy.java:411)
	at app//sootup.core.typehierarchy.ViewTypeHierarchy.superClassOf(ViewTypeHierarchy.java:292)
	at app//sootup.core.typehierarchy.TypeHierarchy.superClassesOf(TypeHierarchy.java:183)
	at app//sootup.callgraph.AbstractCallGraphAlgorithm.findMethodInHierarchy(AbstractCallGraphAlgorithm.java:271)
	at app//sootup.callgraph.ClassHierarchyAnalysisAlgorithm.lambda$resolveCall$1(ClassHierarchyAnalysisAlgorithm.java:89)
	at java.base@11.0.19/java.util.Optional.orElseGet(Optional.java:369)
	at app//sootup.callgraph.ClassHierarchyAnalysisAlgorithm.resolveCall(ClassHierarchyAnalysisAlgorithm.java:89)
	at app//sootup.callgraph.AbstractCallGraphAlgorithm.lambda$resolveAllCallsFromSourceMethod$3(AbstractCallGraphAlgorithm.java:176)
	at java.base@11.0.19/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base@11.0.19/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base@11.0.19/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.19/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.19/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.19/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base@11.0.19/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base@11.0.19/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at app//sootup.callgraph.AbstractCallGraphAlgorithm.processWorkList(AbstractCallGraphAlgorithm.java:144)
	at app//sootup.callgraph.AbstractCallGraphAlgorithm.constructCompleteCallGraph(AbstractCallGraphAlgorithm.java:97)
	at app//sootup.callgraph.ClassHierarchyAnalysisAlgorithm.initialize(ClassHierarchyAnalysisAlgorithm.java:63)
	at app//root.analysis.SootAnalysisTest.callGraphTest(SootAnalysisTest.java:153)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.19/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.19/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


SootAnalysisTest > callGraphTest() FAILED
    sootup.core.frontend.ResolveException at SootAnalysisTest.java:153
1 test completed, 1 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/liumengjiao/Desktop/CI/Benchmark/build/reports/tests/test/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
5 actionable tasks: 2 executed, 3 up-to-date
```
Here is the entrymethod. The statement in `setBugName` is 'this.name = bugName'.
```
    public A(B bug) {
        bug.setBugName("name");
    }
```
And the code, which failed at `initialize`
```
        CallGraphAlgorithm cha =
                new ClassHierarchyAnalysisAlgorithm(view);
        CallGraph cg =
                cha.initialize(Collections.singletonList(entryMethodSignature));
```

Similar error also occurred when resolving another method, but the error message was 'Could not find java.lang.Enum in View. ./file-does-not-exist NoPositionInformation'
I use 'sootup' built from the newest repository.

**Comment by kadirayk** [comment]
Could you submit the whole code block where you set up the view?

**Comment by MaverickMango** [comment]
> Could you submit the whole code block where you set up the view?

```
AnalysisInputLocation<JavaSootClass> inputLocation =
                new JavaClassPathAnalysisInputLocation("build/classes/java/test");
        AnalysisInputLocation<JavaSootClass> cp =
                new JavaClassPathAnalysisInputLocation("build/classes/java/main");
        JavaLanguage language = new JavaLanguage(8);
        Project<JavaSootClass, JavaView> project =
                JavaProject.builder(language).
                        addInputLocation(cp).
//                        addInputLocation(new JavaClassPathAnalysisInputLocation(System.getProperty("java.home") + "/lib/jrt-fs.jar")).//still can not resolve the java.base objects such as java.lang.Object when adding this line
                        addInputLocation(inputLocation).build();

        JavaView view = project.createView(new LRUCacheProvider<>(50));
        ClassType classType = view.getIdentifierFactory().getClassType("xx.xx.A");

        MethodSignature entryMethodSignature =
                JavaIdentifierFactory.getInstance()
                        .getMethodSignature(
                                classType,
                                JavaIdentifierFactory.getInstance()
                                        .getMethodSignature(classType
                                                , "<init>"
                                                , "void"
                                                , List.of(
                                                        new String[]{"xx.xx.B"})
                                        ).getSubSignature());
        SootClass<JavaSootClassSource> sootClass = view.getClass(classType).get();
        Optional<? extends SootMethod> method = view.getMethod(entryMethodSignature);
        Assertions.assertTrue(method.isPresent());
        SootMethod sootMethod = method.get();

        CallGraphAlgorithm cha =
                new ClassHierarchyAnalysisAlgorithm(view);
        CallGraph cg =
                cha.initialize(Collections.singletonList(entryMethodSignature));
        System.out.println(cg);
```

**Comment by swissiety** [comment]
which version of SootUp do you use?

**Comment by JonasKlauke** [comment]
In that version, you have to provide every reachable method as inputlocaction. 
It is complaining about the Object class which is contained in the rt.jar since you configured java 8.
You could either try to point to a java 8 folder or you have to use the module input location since you are using Java above 9.
The Object file you are pointing to in the java home library contains the module name so it should be called java.base.java.lang.Object if I remember correctly.

**Comment by MaverickMango** [comment]
> In that version, you have to provide every reachable method as inputlocaction. It is complaining about the Object class which is contained in the rt.jar since you configured java 8. You could either try to point to a java 8 folder or you have to use the module input location since you are using Java above 9. The Object file you are pointing to in the java home library contains the module name so it should be called java.base.java.lang.Object if I remember correctly.

I am confused because there are some warning reported like the following before the exception, but when I try to resolve another method, it just reports warnings without exception.
```
[Test worker] WARN sootup.core.typehierarchy.TypeHierarchy - Could not find java.lang.Object and stopped there the resolve of superclasses of ...
[Test worker] WARN sootup.core.typehierarchy.TypeHierarchy - Could not find java.util.stream.Collectors and stopped there the resolve of superclasses of ...
...
```

I have to use java11 because of other depencies... i add input location like 'addInputLocation(new JavaModulePathAnalysisInputLocation(System.getProperty("java.home") + "/jmods/java.base.jmod"))` and 'addInputLocation(new JrtFileSystemAnalysisInputLocation())' but both got 'IllegalException' . What should I do to avoid this exception?

**Comment by MaverickMango** [comment]
> which version of SootUp do you use?

the newest built by myself

**Comment by swissiety** [comment]
If you have no rt.jar and the available runtime is from newer than Java8 you can use the JavaModuleView and need to add a `JrtFileSystemAnalysisInputLocation` as inputlocation

**Comment by MaverickMango** [comment]
> If you have no rt.jar and the available runtime is from newer than Java8 you can use the JavaModuleView and need to add a `JrtFileSystemAnalysisInputLocation` as inputlocation

Thanks! it works by adding `JrtFileSystemAnalysisInputLocation` and use `JavaModuleIdentifierFactory` to get classType.
