### ISSUE TITLE
Install SootUp failed

### ISSUE THREAD

**Issue by lianxmfor** [soot-oss/SootUp#890]
I'm sorry for the maybe stupid question that I failed when trying to install SootUp with `Building from Source` section from the [tutorial](https://soot-oss.github.io/SootUp/latest/installation/).

I have no idea how to solve this since I am no familiar with java ecosystem, can someone help to figure out this?

What I did:

```shell
$ git clone https://github.com/secure-software-engineering/SootUp.git
$ cd SootUp
$ mvn install
```

What I got from `mvn intall`:

```shell
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/minimaltestsuite/java6/NoModifierClassTest.java:[2,1] cannot access sootup.java.sourcecode.minimaltestsuite.java6
  error accessing directory /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/javajava.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: sootup/java/sourcecode/minimaltestsuite/java6/����������Test.java
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/frontend/StmtPositionInfoTest.java:[11,43] package jdk.nashorn.internal.ir.annotations does not exist
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SootUp 1.2.1-SNAPSHOT:
[INFO]
[INFO] SootUp ............................................. SUCCESS [  1.214 s]
[INFO] SootUp Core ........................................ SUCCESS [  7.895 s]
[INFO] SootUp Java Core ................................... SUCCESS [  3.099 s]
[INFO] SootUp Java Sourcecode Frontend .................... FAILURE [  0.946 s]
[INFO] SootUp Jimple Frontend ............................. SKIPPED
[INFO] SootUp Java Bytecode Frontend ...................... SKIPPED
[INFO] SootUp Callgraph ................................... SKIPPED
[INFO] SootUp (integration) testing and coverage module ... SKIPPED
[INFO] SootUp Analysis .................................... SKIPPED
[INFO] SootUp Examples .................................... SKIPPED
[INFO] SootUp Coverage Report Module ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.447 s
[INFO] Finished at: 2024-03-13T15:27:15+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project sootup.java.sourcecode: Compilation failure: Compilation failure:
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/minimaltestsuite/java6/NoModifierClassTest.java:[2,1] cannot access sootup.java.sourcecode.minimaltestsuite.java6
[ERROR]   error accessing directory /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/javajava.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: sootup/java/sourcecode/minimaltestsuite/java6/����������Test.java
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/frontend/StmtPositionInfoTest.java:[11,43] package jdk.nashorn.internal.ir.annotations does not exist
```

my mvn version is:
```shell
$ mvn --version                                                                           15:27:16
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /home/linuxbrew/.linuxbrew/Cellar/maven/3.9.6/libexec
Java version: 21.0.1, vendor: Homebrew, runtime: /home/linuxbrew/.linuxbrew/Cellar/openjdk/21.0.1/libexec
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.143.bsk.8-amd64", arch: "amd64", family: "unix"
```

SootUp version is:

```shell
commit 9b219a903ab972ca10a2b5df84a14bc2c1113ec1 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: cde422e7a 733d48474
Author: Kadiray Karakaya <kadiray.k@hotmail.com>
Date:   Mon Mar 11 15:50:09 2024 +0100

    Merge pull request #887 from soot-oss/Interceptors_Package_Change

    Changed interceptors package
```

**Comment by stschott** [comment]
Try to run the following command:
```
mvn install -DskipTests
```

**Comment by swissiety** [comment]
I can't reporduce the problem in "NoModifierClassTest" - can you please execute the testcase in debug mode and find out what the unmappable characters are?

**Comment by JonasKlauke** [comment]
That is probably this testcase αρετηTest

**Comment by JonasKlauke** [comment]
Maybe you are missing utf-8. You might have to check your maven environment

**Comment by lianxmfor** [comment]
> -DskipTests

```
$ mvn install -DskipTests
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/minimaltestsuite/java6/NoModifierClassTest.java:[2,1] cannot access sootup.java.sourcecode.minimaltestsuite.java6
  error accessing directory /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/javajava.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: sootup/java/sourcecode/minimaltestsuite/java6/����������Test.java
[ERROR] /data00/home/lianxiuming/github/SootUp/sootup.java.sourcecode/src/test/java/sootup/java/sourcecode/frontend/StmtPositionInfoTest.java:[11,43] package jdk.nashorn.internal.ir.annotations does not exist
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SootUp 1.2.1-SNAPSHOT:
[INFO]
[INFO] SootUp ............................................. SUCCESS [  1.052 s]
[INFO] SootUp Core ........................................ SUCCESS [  2.433 s]
[INFO] SootUp Java Core ................................... SUCCESS [  0.354 s]
[INFO] SootUp Java Sourcecode Frontend .................... FAILURE [  1.252 s]
[INFO] SootUp Jimple Frontend ............................. SKIPPED
[INFO] SootUp Java Bytecode Frontend ...................... SKIPPED
[INFO] SootUp Callgraph ................................... SKIPPED
[INFO] SootUp (integration) testing and coverage module ... SKIPPED
[INFO] SootUp Analysis .................................... SKIPPED
[INFO] SootUp Examples .................................... SKIPPED
[INFO] SootUp Coverage Report Module ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.377 s
[INFO] Finished at: 2024-03-14T11:18:15+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by lianxmfor** [comment]
> Maybe you are missing utf-8. You might have to check your maven environment

Thanks! After set locale and use https://github.com/soot-oss/SootUp/pull/891 the `SootUp Jimple Frontend` success passed!

**Comment by lianxmfor** [comment]
> > Maybe you are missing utf-8. You might have to check your maven environment
> 
> Thanks! After set locale and use #891 the `SootUp Jimple Frontend` success passed!

But then the `SootUp Java Bytecode Frontend` failed:

```shell
[ERROR] Tests run: 22, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 0.714 s <<< FAILURE! -- in sootup.java.bytecode.frontend.JavaModuleViewTest
[ERROR] sootup.java.bytecode.frontend.JavaModuleViewTest.testGeneralClassReceivalFromModule -- Time elapsed: 0.555 s <<< FAILURE!
org.opentest4j.AssertionFailedError: actual: 7546 ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
        at sootup.java.bytecode.frontend.JavaModuleViewTest.testGeneralClassReceivalFromModule(JavaModuleViewTest.java:64)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   JavaModuleViewTest.testGeneralClassReceivalFromModule:64 actual: 7546 ==> expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 41, Failures: 1, Errors: 0, Skipped: 7
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SootUp 1.2.1-SNAPSHOT:
[INFO]
[INFO] SootUp ............................................. SUCCESS [  0.959 s]
[INFO] SootUp Core ........................................ SUCCESS [  3.809 s]
[INFO] SootUp Java Core ................................... SUCCESS [  2.188 s]
[INFO] SootUp Java Sourcecode Frontend .................... SUCCESS [  5.900 s]
[INFO] SootUp Jimple Frontend ............................. SUCCESS [20:17 min]
[INFO] SootUp Java Bytecode Frontend ...................... FAILURE [01:31 min]
[INFO] SootUp Callgraph ................................... SKIPPED
[INFO] SootUp (integration) testing and coverage module ... SKIPPED
[INFO] SootUp Analysis .................................... SKIPPED
[INFO] SootUp Examples .................................... SKIPPED
[INFO] SootUp Coverage Report Module ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22:01 min
[INFO] Finished at: 2024-03-14T11:49:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project sootup.java.bytecode: There are test failures.
```
content of the log file:

```shell
$ cat /SootUp/sootup.java.bytecode/target/surefire-reports/sootup.java.bytecode.frontend.JavaModuleViewTest.txt
-------------------------------------------------------------------------------
Test set: sootup.java.bytecode.frontend.JavaModuleViewTest
-------------------------------------------------------------------------------
Tests run: 22, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 0.714 s <<< FAILURE! -- in sootup.java.bytecode.frontend.JavaModuleViewTest
sootup.java.bytecode.frontend.JavaModuleViewTest.testGeneralClassReceivalFromModule -- Time elapsed: 0.555 s <<< FAILURE!
org.opentest4j.AssertionFailedError: actual: 7546 ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
        at sootup.java.bytecode.frontend.JavaModuleViewTest.testGeneralClassReceivalFromModule(JavaModuleViewTest.java:64)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```
```

**Comment by lianxmfor** [comment]
I get it! At openjdk 11.0.22 the `amount of java.base classes` is 7546 obviously not in the range (5500, 6500):

```shell
$ java --version
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment Homebrew (build 11.0.22+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.22+0, mixed mode)
```

Maybe SootUp need to fix this or put some information on README? I am glad to do this.
