### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: Failed to apply sootup.java.core.interceptors.TypeAssigner

### ISSUE THREAD

**Issue by sahilagichani14** [soot-oss/SootUp#988]
### What happened?

when running the mockito-core-5.3.1.jar, or logback-core-1.4.7.jar with java 8 version but without DefaultRTJarAnalysisInputLocation() in input location, fails at "The path from 'java.lang.RuntimeException' to java.lang.Throwable cannot be found!"

### Version

Latest develop branch

### Relevant log output

```shell
java.lang.IllegalStateException: Failed to apply sootup.java.core.interceptors.TypeAssigner@550fe9d7 to <org.mockito.internal.MockedStaticImpl: void verify(org.mockito.MockedStatic$Verification,org.mockito.verification.VerificationMode)>

	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:240)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at sootup.java.bytecode.interceptors.typeresolving.TypeResolverTest.applyTrToJar(TypeResolverTest.java:351)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at sootup.java.bytecode.interceptors.typeresolving.TypeResolverTest.testTrWithoutLs(TypeResolverTest.java:292)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
Caused by: java.lang.IllegalStateException: The path from 'java.lang.RuntimeException' to java.lang.Throwable cannot be found!
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.getExceptionPath(AugEvalFunction.java:252)
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.getLeastCommonExceptionType(AugEvalFunction.java:274)
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.evaluate(AugEvalFunction.java:195)
	at sootup.java.core.interceptors.typeresolving.TypeResolver.applyAssignmentConstraint(TypeResolver.java:215)
	at sootup.java.core.interceptors.typeresolving.TypeResolver.resolve(TypeResolver.java:74)
	at sootup.java.core.interceptors.TypeAssigner.interceptBody(TypeAssigner.java:42)
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:234)
	... 9 more
```

**Comment by yyh834771838** [comment]
I meet the some exception. Have you solved it?

**Comment by sahilagichani14** [comment]
> I meet the some exception. Have you solved it?

This is taken care by the PR, https://github.com/soot-oss/SootUp/pull/989. once its merged it will give a warning instead of an exception. or you could add new DefaultRTJar in inputlocations
