### ISSUE TITLE
[Bug]: IllegalArgumentException thrown in some nested try-catch-finally scenarios

### ISSUE THREAD

**Issue by stschott** [soot-oss/SootUp#996]
### What happened?

In some nested try-catch-finally scenarios there is an `IllegalArgumentException` thrown by the `StmtGraph`.

Example code:
```java
private static String test0(File storedResults) throws Exception {
   try {
        FileInputStream file = new FileInputStream(storedResults);
        try {
            ObjectInputStream stream = new ObjectInputStream(file);
            try {
                return (String) stream.readObject();
            } finally {
                stream.close();
            }
        } finally {
            file.close();
        }
    } catch (Exception e) {
        throw new Exception(e);
    }
}
```

A failing test case has already been provided to branch [fix/nestedTryCatchFinally](https://github.com/soot-oss/SootUp/tree/fix/nestedTryCatchFinally).

### Version

Latest develop branch

### Relevant log output

```shell
java.lang.IllegalArgumentException: Invalid StmtGraph. A Trap is not created as a traps endStmt was not visited during the iteration of all Stmts.

	at sootup.core.graph.StmtGraph$BlockGraphIteratorAndTrapAggregator.getTraps(StmtGraph.java:495)
	at sootup.core.graph.MutableBlockStmtGraph.buildTraps(MutableBlockStmtGraph.java:1626)
	at sootup.core.graph.ForwardingStmtGraph.buildTraps(ForwardingStmtGraph.java:133)
	at sootup.core.model.Body.getTraps(Body.java:120)
	at sootup.java.bytecode.TryCatchFinallyTests.testNestedTryCatchFinally(TryCatchFinallyTests.java:49)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by sahilagichani14** [comment]
Jimple Generated by Soot
`private java.lang.String test0(java.io.File) throws java.lang.Exception
    {
        unknown $stack7, storedResults, file, $stack8, stream, $stack9, l4, $stack10, $stack11, $stack12, l6, $stack13, l5, this;

        this := @this;

        storedResults := @parameter0;

     label01:
        $stack7 = new java.io.FileInputStream;

        specialinvoke $stack7.<init>(storedResults);

        file = $stack7;

     label02:
        $stack8 = new java.io.ObjectInputStream;

        specialinvoke $stack8.<init>($stack7);

        stream = $stack8;

     label03:
        $stack9 = virtualinvoke $stack8.readObject();

        l4 = (java.lang.String) $stack9;

     label04:
        virtualinvoke $stack8.close();

     label05:
        virtualinvoke $stack7.close();

     label06:
        return l4;

     label07:
        $stack13 := @caughtexception;

        l5 = $stack13;

     label08:
        virtualinvoke $stack8.close();

        throw $stack13;

     label09:
        $stack12 := @caughtexception;

        l6 = $stack12;

     label10:
        virtualinvoke $stack7.close();

        throw $stack12;

     label11:
        $stack10 := @caughtexception;

        file = $stack10;

        $stack11 = new java.lang.Exception;

        specialinvoke $stack11.<init>($stack10);

        throw $stack11;

        nop;

        catch java.lang.Throwable from label03 to label04 with label07;
        catch java.lang.Throwable from label07 to label08 with label07;
        catch java.lang.Throwable from label02 to label05 with label09;
        catch java.lang.Throwable from label07 to label10 with label09;
        catch java.lang.Exception from label01 to label06 with label11;
        catch java.lang.Exception from label07 to label11 with label11;
    }`

**Comment by swissiety** [comment]
will most likely be fixed by the StmtGraphIterator fix
